server:
  port: 9940
  
spring:
  application:
    name: demo-auth
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: ${jdbc_url}
    username: ${jdbc_username}
    password: ${jdbc_password}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.spatome.demo.core.entity

logging:
  file: /data/cloud/logs/demo-auth/demo.log