eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5  #心跳
    lease-expiration-duration-in-seconds: 15
  client:
    registry-fetch-interval-seconds: 5 #定时刷新本地缓存时间
    service-url:
      defaultZone: http://root:root@192.168.0.199:9999/eureka/

server:
  port: 9998

spring:
  application:
    name: demo-cloud-config
  profiles:
    active: native
  cloud:
    config:
      label: master
      server:
        native:
          search-locations:
            - file:./config/ #注意。表示执行命令的目录

ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 50000
  ServerListRefreshInterval: 2000

hystrix:
  command:
    default:
      execution:
        isolation: 
          thread:
            timeoutInMilliseconds: 110000