server:
  port: 9990

spring:
  application:
    name: demo-cloud-gateway

zuul:
  routes:
    auth:
      path: /auth/**
      service-id: DEMO-AUTH
    user:
      path: /user/**
      service-id: DEMO-USER
    account:
      path: /account/**
      service-id: DEMO-ACCOUNT
    test:
      path: /test/**
      service-id: DEMO-TEST

logging:
  file: /data/cloud/logs/demo-cloud-gateway/demo.log