server:
  port: 9990

spring:
  application:
    name: demo-cloud-gateway

zuul:
  routes:
    auth:
      path: /auth/**
      service-id: DEMO-AUTH
    user:
      path: /user/**
      service-id: DEMO-USER
    account:
      path: /account/**
      service-id: DEMO-ACCOUNT
    test:
      path: /test/**
      service-id: DEMO-TEST
    tmp:
      path: /tmp/**
      service-id: DEMO-TMP
  ratelimit:  #网关限流
    enabled: false
    behind-proxy: true
    default-policy:
      limit: 100
      type:
        - ORIGIN
        #- USER
        #- URL