server:
  port: 9999

spring:
  application:
    name: demo-cloud-register
  security:
    user:
      name: root
      password: root

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5  #心跳
    lease-expiration-duration-in-seconds: 15 #没有心跳淘汰时间
  server:
    enable-self-preservation: false #自我保护
    renewal-threshold-update-interval-ms: 120000 #心跳阈值计算周期 
    eviction-interval-timer-in-ms: 5000 #主动失效检测
    use-read-only-response-cache: false #禁用readOnlyCacheMap
  client:
    register-with-eureka: false #指示此实例是否应将其信息注册到eureka服务器以供其他人发现。在某些情况下，您不希望发现实例，而您只想发现其他实例。
    fetch-registry: false #指示该客户端是否应从eureka服务器获取eureka注册表信息
    service-url:
      defaultZone: http://root:root@192.168.0.199:${server.port}/eureka/