server:
  port: 9950

spring:
  application:
    name: demo-test

logging:
  file: /cloud/logs/demo-test/demo.log

#hystrix:
#  command:
#    "AccountClient#addAccountAmount(String,String)":
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 15000
